### ISSUE TITLE
Unicode exception

### ISSUE THREAD

**Issue by wholewheattoast** [bbangert/lettuce_webdriver#55]
Exception:

``` Then I should see "Search Results for Iñtërnâtiônàlizætiøn" within 10 seconds                                                            # home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/lettuce_webdriver/webdriver.py:152
    Traceback (most recent call last):
      File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/lettuce_webdriver/webdriver.py", line 153, in should_see_in_seconds
        wait_for_content(step, world.browser, text, int(timeout))
      File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/lettuce_webdriver/webdriver.py", line 62, in wait_for_content
        if contains_content(world.browser, content):
      File "/home/shawn/.virtualenvs/deus_lex/local/lib/python2.7/site-packages/lettuce_webdriver/webdriver.py", line 37, in contains_content
        .format(content=content))):
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 20: ordinal not in range(128)```

Full test of scenario:

    Scenario: 1. I want the search bar on the landing page to work as expected
        Given I point browser to "/"
        And I fill in $("#main-search input[name=q]") with "Iñtërnâtiônàlizætiøn"
        And I click $("#main-search .btn-default")
        Then I should see "Search Results for Iñtërnâtiônàlizætiøn" within 10 seconds

**Comment by bsvetchine** [comment]
+1 I have the same exception using @step('I select "(.*?)" from "(.*?)"$')
